eduka/users/views.py
## views.py inside users folder
# -*- coding: utf-8 -*-


from flask import (Blueprint, render_template, url_for,
                   flash, redirect, request, abort)
from eduka import login_manager, db
from eduka.users.user_forms import LoginForm, RegistrationForm, ForgotAccountForm, EditProfileForm
from flask_login import logout_user, login_required, login_user, current_user
from eduka.models import User, Post
from eduka.utils.other_utils import populate_edit_form, allowed_file
from eduka.utils.database_utils import update_user_info
from werkzeug.utils import secure_filename

users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates/users')




@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    ## CHECK IF USER IS ALREADY LOGIN
    if current_user.is_authenticated:
		## we will need to change the link to logout
        return redirect(url_for('core.home'))

    if form.validate_on_submit():
        email = form.email.data
        pwd = form.password.data

        ## To log the user, need:
        ## 1 - check the user exist (is not none)
        ## 2 - check password math
        ## 3 - log user in

        ## 1 - check the user exist (is not none)
        usr = User.query.filter_by(email=email).first()

        ## 2 - check password math
        if usr.check_password(pwd) and usr is not None:
            login_user(usr)

        ## here we will add the next -- to forward the user
        ## to the intended page
            next = request.args.get('next')
        # is_safe_url should check if the url is safe for redirects.
        # See http://flask.pocoo.org/snippets/62/ for an example.
            '''
            if not is_safe_url(next):
                return abort(400)

            '''

            return redirect(url_for('users.my_account', public_id=usr.public_id))

        else:
            flash(" The user doen't exist or the credentials are not correct, please try again!", 'danger')

    return render_template('login.html', form=form, title='Login page')



@users_blueprint.route('/registration', methods=['GET', 'POST'])
def registration():

    form = RegistrationForm()

    if form.validate_on_submit():
        email = form.email.data
        username = form.username.data
        pwd = form.password.data

        ## save the data in the database
        new_usr = User(email=email, username=username, pwd=pwd)
        db.session.add(new_usr)
        db.session.commit()

        return redirect(url_for('users.login'))

    return render_template('registration.html', form=form, title='Regsitration page')



@users_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash("You've been log out!", 'warning')
    return redirect(url_for('users.login'))


######################################################
##													##
##               ACCOUNT PAGE       				##
##													##
######################################################


@users_blueprint.route('/<string:public_id>/account', methods=['GET', 'POST'])
@login_required
def my_account(public_id):

    title = "Ma page de profile"
    edit_form = EditProfileForm()
    ## The current_user is automatically passsed to the jinja template
    ## we need to to get the current_user Posts

    user = User.query.filter(User.public_id==public_id).first()
    ## get all posts for the user in a descending order
    ## we could do it in one line, but prefer multiple
    ## lines to minimise mistakes
    p = Post.query.filter_by(user_id=user.id)
    p_desc = p.order_by(Post.date_posted.desc())
    posts = p_desc.all()

    ##### edit user ######
    populate_edit_form(user=user, form=edit_form)

    if edit_form.validate_on_submit():
        from eduka.utils.save_file import upload_file_to_s3
        ## the form is okay, so we can save to the database
        #print("from validate on submit()")
        new_username = request.form['username']
        new_email = request.form['email']
        new_bio = request.form['bio']
        avatar_pic_file = request.files['avatar_pic']

        ### SAVING THE IMAGE TO S3 IF NECESSARY
        file_s3_url = ""
        if avatar_pic_file and allowed_file(avatar_pic_file.filename):
            ## if there is a new avatar image we will upload it to S3
            file_s3_url = upload_file_to_s3(file=avatar_pic_file)

        new_user_info = {
            "username": new_username,
            "email": new_email,
            "about_me":new_bio,
            "url":file_s3_url,
            "current_user":current_user
        }

        ## Create a diff calculator to check if user has updated any info
        ## before calling rhe database for saving

        update_user_info(user_info=new_user_info)

        return redirect(url_for('users.my_account', public_id=current_user.public_id))

    #print(f'form errors: {edit_form.errors}')
    return render_template('account.html', user=user,
                           user_id=user.id,
                           posts=posts,title=title,
                           form = edit_form)


@users_blueprint.route('/clap/<string:post_public_id>/<action>')
def clap_action(post_public_id, action):
    ## clap the post

    post = Post.query.filter(Post.public_id == post_public_id).first()
    if action == 'clap' and current_user.is_authenticated:
        ## we will need to update the postclap with the
        ## current_user public_id
        current_user.clap_post(post)
        db.session.commit()

    elif action == 'unclap' and current_user.is_authenticated:
        current_user.unclap_post(post)
        db.session.commit()
    else:
        ## here we will redirect user to authenticate
        return redirect(url_for('users.login'))

    # referrer = request.headers.get("Referer")
    url = request.values.get("url") or request.headers.get("Referer")
    #print(url)

    response = redirect(url)
    return response




######################################################
##													##
##               FORGOT PASSWORD      				##
##													##
######################################################


@users_blueprint.route('/forgot', methods=['GET', 'POST'])
def forgot_pwd():

	form = ForgotAccountForm()

	if form.validate_on_submit():
		## send an email with a reset link to the user

		email_provided = form.email.data

		## 1- Check to see if email is in database
		## 2- Send email with reset link to user registered email address

		print(f'Info: {form.email.data}')

		return redirect(url_for('users.login'))

	return render_template('forgot_pwd.html', form=form, legend='Forgot Password')

eduka/users/templates/users/account.html
<!-- UPDATE ACCOUNT -->

{% extends 'base.html' %}

{% block content %}
    <!----- Slidding right section --->
    {% if current_user.id == user.id %}
    <div class="slide-in from-right">
      <div class="slide-in-content">
        {% with user=user, form=form %}
        {% include 'edit_profile.html' %}
        {% endwith %}
      </div>
    </div>
    {% endif %}
    <!----- //Slidding right section --->

    <section class="hero is-prime-color">
      <div class="hero-body">
        <div class="container">
          <!-- .media -->
          <article class="media" >
            <figure class="media-left">
              <p class="image is-64x64">
                <img class="is-rounded" src="{{ user.profile_image_link }}">
              </p>
            </figure>
            <div class="media-content" style="max-width:40%">
              <div class="content">
                <p>
                  <strong>{{ user.username }}</strong> <small>@{{ user.username }}</small>
                  <br>
                    {{ user.bio }}
                </p>
              </div>
              <nav class="level is-mobile">
                <div class="level-left">
                  {% if current_user.id == user.id %}
                  <a class="level-item" id="toggle">
                    <span class="icon is-small"><i class="fas fa-user-edit"></i></span>
                  </a>
                  {% endif %}
                  <a class="level-item">
                    <span class="icon is-small"><i class="fas fa-heart"></i></span>
                  </a>
                  <p class="level-item">collections: {{ posts|length }}</p>
                </div>
              </nav>
            </div>

            {# right side to add info such as nbr collection, nbr like, etc #}

            <!-- <div class="media-right">
              <button class="delete"></button>
            </div> -->
          </article>
          <!-- /.media -->
        </div>
      </div>

    </section>

    {# ************ LEFT SIDE *************************** #}
    <section class="section">
      <div class="container">
        <div class="row">
          <div class="columns">

            <div class="column is-2-widescreen">
              {# LEFT SIDE #}
              <section class="section">
                <h3 class="subtitle is-4"> Filtrer par:</h3>
                {# start of the card - need to change this for a table #}
                <div class="menu">
                  <ul class="menu-list">
                    <li> <a href="#" class="is-active">All</a> </li>
                    <li> <a href="#">Python</a> </li>
                    <li> <a  href="#">Javascript</a> </li>
                    <li> <a href="#">Flask</a> </li>
                    <li> <a href="#">Git</a> </li>
                  </ul>
                </div>

              </section>
            </div>


            {# ********** RIGHT SIDE  ************** #}
            <div class="column is-10">
              <section class="section">
                <h3 class="subtitle is-4"> Mes collections</h3>
                {# we will dive the different columns#}
                <div class="columns is-multiline">
                  {# start the for loop to get all the posts #}
                  {% for post in posts %}
                    <div class="column is-one-third">
                      {# start of the card #}
                      <div class="card">
                        <div class="card-image">
                          <figure class="image is-4by3">
                            <img src="{{ post.post_image_link }}" alt="Post Image">
                          </figure>
                        </div>
                        <div class="card-content">
                          <div class="media">
                            <div class="media-content">
                              <p class="title is-5">{{ post.title }}</p>
                              <p class="subtitle is-6">{{ post.date_posted|datetimeformat }}</p>
                            </div>
                          </div>

                          <div class="content">
                            {{ post.summary|truncate(70, True)|safe }}
                          </div>
                          <a href="{{ url_for('posts.show_post',post_public_id=post.public_id)}}" class="button is-primary issmall">Voir collection</a>
                        </div>
                      </div>
                      {# end of the card #}
                    </div>
                  {% endfor %}

                </div>

              </section>


            </div>

          </div>

      </div>


    </section>


{% endblock %}

eduka/users/templates/users/edit_profile.html
<!-- edit_profile.html -->

<form method="POST" enctype="multipart/form-data" >
  <div class="media u-margin-top-small">
    <div class="media-left">
      <h1 class="title is-4" > Éditer mon profile </h1>
    </div>
    <div class="media-right">
      <a class="delete" id="toggle-delete"></a>
    </div>
  </div>


  {# This hidden_tag is a CSRF security feature. #}
  {{ form.hidden_tag() }}

  <div class="field u-margin-top-medium">
  <!-- <label class="label" for="username">Ajoutez une photo à votre profile</label> -->
  {{ form.avatar_pic.label(class="label")}}

  <div class="file is-small is-boxed has-name">
    <label class="file-label">
      <!-- <input class="file-input" type="file" name="resume"> -->
      {{ form.avatar_pic(class="file-input")}}
      <span class="file-cta">
        <span class="file-icon">
          <i class="fas fa-upload"></i>
        </span>
        <span class="file-label">
          votre avatar…
        </span>
      </span>
      <span class="file-name">
        {%  if filename %}
        {{ filename }}
        {% else %}
        votre_photo.png
        {% endif %}

      </span>
    </label>
  </div>
</div>

  <div class="field">
    {{ form.username.label(class="label") }}
    <div class="control has-icons-left has-icons-right">
      {{ form.username(class="input", placeholder="nom d'utilisateur") }}
      <span class="icon is-small is-left">
        <i class="fas fa-user"></i>
      </span>
      <span class="icon is-small is-right">
        <i class="fas fa-check"></i>
      </span>
    </div>
    <p class="help is-success">Choose a plaisant username</p>
  </div>


  <div class="field">
    {{ form.email.label(class="label") }}
    <div class="control has-icons-left has-icons-right">
      {{ form.email(class="input", placeholder="Votre email") }}
      <span class="icon is-small is-left">
        <i class="fas fa-envelope"></i>
      </span>
      <span class="icon is-small is-right">
        <i class="fas fa-exclamation-triangle"></i>
      </span>
    </div>
    <p class="help is-success">We'll never share your email with anyone else</p>
    {% if form.email.errors %}
        <ul class="errors">{% for error in form.email.errors %}<li>{{ error }}</li>{% endfor %}</ul>
    {% endif %}
  </div>

  <div class="field">
    {{ form.bio.label(class="label") }}
    <div class="control">
      {{ form.bio(class="textarea", placeholder="Un bref bio vous concernant") }}
    </div>
    <p class="help is-success">Écrire une petite biographie à propos de vous</p>
  </div>


  <div class="field is-grouped">
    <div class="control">
      {{ form.update_submit(class='button is-primary is-medium') }}
    </div>
  </div>

</form>

eduka/users/templates/users/forgot_pwd.html
{% extends 'base.html' %}


{% block content %}

          <div class="limiter">
            <div class="container-login100">

              <div class="login-box">

                <!-----------Start of left box ----->
                <div class="left-box">

                  <div class="container">
                    {# Column left for the text#}
                    <h1 class="left-box-title"> Retour à la connexion</h1>

                    <div class="level">
                      <div class="level-item has-text-centered">
                        <div>
                          <a href="{{url_for('users.login')}}" class="button is-primary">Je me connecte</a>
                        </div>
                      </div>
                    </div>

                  </div>

                </div>



                <!-----------Start of right box ----->
                <div class="right-box" style="padding-top: 231px">

                  <h1 class="title is-4"> {{ legend }} </h1>

                  <form method="POST">

                    {# This hidden_tag is a CSRF security feature. #}
                    {{ form.hidden_tag() }}

                    <div class="field">
                      {{ form.email.label(class="label") }}
                      <div class="control has-icons-left has-icons-right">
                        {{ form.email(class="input", placeholder="Votre email") }}
                        <span class="icon is-small is-left">
                          <i class="fas fa-envelope"></i>
                        </span>
                        <span class="icon is-small is-right">
                          <i class="fas fa-exclamation-triangle"></i>
                        </span>
                      </div>
                      <p class="help is-success">This username is available</p>
                    </div>


                    <div class="field is-grouped">
                      <div class="control">
                        {{ form.submit(class="button is-primary is-medium") }}
                      </div>
                    </div>


                  </form>

                </div>


              </div>
              <!-----------// end login-box ----->
            </div>
          </div>


{% endblock %}

eduka/users/templates/users/login.html
<!-- LOGIN.HTML -->


{% extends 'base.html' %}

{% block content %}

          <div class="limiter">
            <div class="container-login100">

              <div class="login-box">

                <!-----------Start of left box ----->
                <div class="left-box">

                  <div class="container">
                    {# Column left for the text#}
                    <h1 class="left-box-title"> Je n'ai pas de compte. </h1>

                    <div class="level">
                      <div class="level-item has-text-centered">
                        <div>
                          <a href="{{url_for('users.registration')}}" class="button is-primary">Je m'inscrit gratuitement</a>
                        </div>
                      </div>
                    </div>

                  </div>

                </div>



                <!-----------Start of right box ----->
                <div class="right-box" style="padding-top: 144px">

                  <h1 class="title is-4"> Renseignez vos identifiants: </h1>
                  <div class="row">
                    {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}

                  </div>

                  {% with messages = get_flashed_messages(with_categories=true) %}
                  <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
                  {% if messages %}
                  {% for category, message in messages %}
                  <div class="notification is-warning">
                    <button class="delete"></button>
                    {{ message }}
                  </div>
                  {% endfor %}
                  {% endif %}
                  {% endwith %}

                  <form method="POST">

                    {# This hidden_tag is a CSRF security feature. #}
                    {{ form.hidden_tag() }}

                    <div class="field">
                      {{ form.email.label(class="label") }}
                      <div class="control has-icons-left has-icons-right">
                        {{ form.email(class="input", placeholder="Votre email") }}
                        <span class="icon is-small is-left">
                          <i class="fas fa-envelope"></i>
                        </span>
                        <span class="icon is-small is-right">
                          <i class="fas fa-exclamation-triangle"></i>
                        </span>
                      </div>
                      <p class="help is-success">This username is available</p>
                    </div>



                    <div class="field">
                      {{ form.password.label(class="label") }}
                      <div class="control has-icons-left has-icons-right">
                        {{ form.password(class="input", placeholder="mot de passe") }}
                        <span class="icon is-small is-left">
                          <i class="fas fa-lock"></i>
                        </span>
                      </div>
                      <p class="help is-success">This username is available</p>
                    </div>

                    <div class="field">
                      <div class="control">
                        <label class="checkbox">
                          {{ form.remember(class="form-check-input") }}
                          {{ form.remember.label()}}
                        </label>
                      </div>
                    </div>


                    <div class="field is-grouped">
                      <div class="control">
                        {{ form.submit(class='button is-primary is-medium') }}
                      </div>
                    </div>

                    <div class="field is-grouped">
                      <div class="control">
                        <a href="{{ url_for('users.forgot_pwd') }}">Mot de passe oublié?</a>
                      </div>
                    </div>

                  </form>

                </div>


              </div> <!-----------// end login-box ----->
            </div>
          </div>



{% endblock %}

eduka/users/templates/users/registration.html
<!-- REGISTER.HTML -->

{% extends 'base.html' %}

{% block content %}

<div class="limiter">
  <div class="container-login100">

    <div class="login-box">

      <!-----------Start of right box ----->
      <div class="left-box">

        <div class="container">
          {# Column left for the text#}
          <h1 class="left-box-title" > J'ai déjà un compte. </h1>

          <div class="level">
            <div class="level-item has-text-centered">
              <div>
                <!-- <h1 class="title is-2 has-text-white"> Je crée mon compte!</h1> -->
                <!-- <p class="title is-6 has-text-white">OU</p> <br> -->
                <a href="{{url_for('users.login')}}" class="button is-primary">Je me connecte</a>
              </div>
            </div>
          </div>

        </div>


      </div>




          <div class="right-box">

              <h2 class="title is-4"> Je crée un compte!</h2>

                <div class="row">
                  {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}

                </div>

                <form method="POST">

                  {# This hidden_tag is a CSRF security feature. #}
                  {{ form.hidden_tag() }}

                  <div class="field">
                    {{ form.username.label(class="label") }}
                    <div class="control has-icons-left has-icons-right">
                      {{ form.username(class="input", placeholder="nom d'utilisateur") }}
                      <span class="icon is-small is-left">
                        <i class="fas fa-user"></i>
                      </span>
                      <span class="icon is-small is-right">
                        <i class="fas fa-check"></i>
                      </span>
                    </div>
                    <p class="help is-success">Choose a plaisant username</p>
                  </div>


                  <div class="field">
                    {{ form.email.label(class="label") }}
                    <div class="control has-icons-left has-icons-right">
                      {{ form.email(class="input", placeholder="Votre email") }}
                      <span class="icon is-small is-left">
                        <i class="fas fa-envelope"></i>
                      </span>
                      <span class="icon is-small is-right">
                        <i class="fas fa-exclamation-triangle"></i>
                      </span>
                    </div>
                    <p class="help is-success">We'll never share your email with anyone else</p>
                  </div>


                  <div class="field">
                    {{ form.password.label(class="label") }}
                    <div class="control has-icons-left has-icons-right">
                      {{ form.password(class="input", placeholder="mot de passe") }}
                      <span class="icon is-small is-left">
                        <i class="fas fa-lock"></i>
                      </span>
                    </div>
                    <p class="help is-success">8 characters min.</p>
                  </div>

                  <div class="field">
                    {{ form.re_password.label(class="label") }}
                    <div class="control has-icons-left has-icons-right">
                      {{ form.re_password(class="input", placeholder="re-taper votre mot de passe") }}
                      <span class="icon is-small is-left">
                        <i class="fas fa-lock"></i>
                      </span>
                    </div>
                    <p class="help is-success">8 characters min.</p>
                  </div>

                  <div class="field">
                    <div class="control">
                      <label class="checkbox">
                        <input type="checkbox">
                        Je suis d'accord avec <a href="#">les termes et conditions</a>
                      </label>
                    </div>
                  </div>

                  <div class="field is-grouped">
                    <div class="control">
                      {{ form.submit(class='button is-primary is-medium') }}
                    </div>
                  </div>

                </form>


            </div>

        </div>

  </div>
</div>




{% endblock %}