eduka/posts/views.py
## views.py inside post folder
# -*- coding: utf-8 -*-


from flask import (Blueprint, render_template, url_for,
                   flash, redirect, request, abort)
from eduka import login_manager, db
from eduka.posts.post_form import AddPostForm
from flask_login import login_required, current_user
from eduka.models import User, Post, PostLink, PostView

from eduka.utils.database_utils import (saving_post, add_tags, saving_links,
                                        saving_views, update_nbr_views,
                                        update_links)
from eduka.utils.other_utils import populate_form
from datetime import datetime as dt, timedelta

posts_blueprint = Blueprint('posts',
                            __name__,
                            template_folder='templates/posts')


@posts_blueprint.route('/publier', methods=['GET','POST'])
@login_required
def add_post():

    title = 'Écrire votre publication'
    ## adding 7 days for the end date
    seven_days = timedelta(days=7)

    form = AddPostForm()

    form.start_date.data = dt.now();
    form.end_date.data = dt.now() + seven_days;

    if form.validate():
        pass
        ##print('******* is valid!')

    if form.validate_on_submit():
        ###print('Has validated on submit')

        author_id = current_user.id;

        title = form.post_title.data;
        summary = form.post_summary.data;
        start_date = form.start_date.data;
        end_date = form.end_date.data;
        level_beg = form.start_level.data;
        level_end = form.end_level.data;
        post_tags = form.post_tags.data;
        privacy_level = form.post_privacy.data;

        ## to get the links and titles
        post_link_titles = request.form.getlist('link1_title');
        post_links = request.form.getlist('link1')

        ## save the post without the links
        post = Post(title=title, summary=summary,
                    date_start=start_date, date_end=end_date,
                    level_beg=level_beg, level_end=level_end,
                    privacy_level=privacy_level, user_id=author_id)

        ## saving posts using the database_utils
        saving_post(post)

        # removing all the spaces
        post_tags.split(", ")
        tags = post_tags.split(",")
        for tag in tags:
            n_tag = ''.join(tag.split())
            post_tag = add_tags(n_tag.lower())
            print(post_tag)
            post.tags.append(post_tag)

        db.session.commit()

        ## saving links
        saving_links(links=post_links, titles=post_link_titles, post_id=post.id)
        ## saving the number of views
        saving_views(post_id=post.id)



        ## empty the fieldsof the form
        form.post_title.data = '';
        form.post_summary.data = '';
        form.start_date.data = dt.now();
        form.end_date.data = dt.now() + seven_days;
        form.start_level.data = 'bg';
        form.end_level.data = 'exp';
        form.post_privacy.data = 'pbl';

        flash (u'New Post Created!', 'is-success')

        return redirect(url_for('posts.add_post'))

    #print(f'form errors: {form.errors}')

    return render_template('create_post.html', title=title, form=form)



@posts_blueprint.route('/post/<string:post_public_id>')
def show_post(post_public_id):

    ## let get the post

    post = Post.query.filter(Post.public_id==post_public_id).first_or_404()
    author = User.query.filter(User.id == post.user_id).first_or_404()
    postlinks = post.links
    views = 0
    ## check to see if the
    if post.nbr_views:
        views = post.nbr_views[0].nbr_views
        views+=1
    else:
        views = 1
        ## adding number of views for the page
        saving_views(post_id=post.id)

    ## get all the Tag objects for the post
    tags_obj = post.tags
    ##print(f'tags: {post.tags}')
    tags = []
    for t in tags_obj:
        tags.append(t.name)



    #tags = tags_str.split(",")
    ##print(f"tags: {tags}")
    title = post.title

    ## updated the database with the new number of views
    ## adding number of views for the page

    update_nbr_views(post.id)

    return render_template('post.html', title=title, post=post,
                           links=postlinks, author=author, views=views, tags=tags)





@posts_blueprint.route('/update/<string:post_public_id>',methods=['GET', 'POST'])
@login_required
def update_post(post_public_id):
    form = AddPostForm()
    post = Post.query.filter(Post.public_id==post_public_id).first_or_404()
    nbr_links = len(post.links)

    if current_user.id != post.user_id:
        ## the if statement here, makes sure that only the author can update the post
        ## print(f'current user id: {current_user.id}, post author id: {post.user_id}')
        return redirect(url_for('posts.show_post', post_id=post.id))

    ## call the populate form from the utils module
    populate_form(post=post, form=form)

    ##### check and submit the form #####
    ## only update the content and title here
    ## need to change the database relationships
    if form.validate_on_submit():
        ''' saving the post '''
        ## to get the links and titles
        new_links = {
            'l_titles': request.form.getlist('link1_title'),
            'links': request.form.getlist('link1')
        }
        #post_link_titles = request.form.getlist('link1_title');
        #post_links = request.form.getlist('link1')

        ## save the post without the links
        post.title = request.form['post_title']
        post.summary = request.form['post_summary']
        post.start_date = request.form['start_date']
        post.end_date = request.form['end_date']
        post.level_beg = request.form['start_level']
        post.level_end = request.form['end_level']
        post_tags = request.form['post_tags']
        post.privacy_level = request.form['post_privacy']
        post.date_updated = dt.utcnow()
        ## updating tags
        tags = post_tags.split(", ")
        for tag in tags:
            #tag.strip()
            ## to remove all whitespaces
            n_tag = ''.join(tag.split())
            post_tag = add_tags(n_tag.lower())
            print(post_tag)
            post.tags.append(post_tag)

        db.session.commit()

        ## check to see if there have been changes and save links
        ## if necessary
        update_links(post_links=post.links,
                     new_links=new_links, post_id=post.id)

        ### do a return to the post view page
        return redirect(url_for('posts.show_post',
                                post_public_id=post.public_id))


    return render_template('update_post.html', form=form,
                           nbr_links=nbr_links, post=post)



@posts_blueprint.route('/delete/<int:post_id>')
@login_required
def delete_post(post_id):
    pass

eduka/posts/templates/posts/create_post.html
<!-- CREATE_POST.HTML -->


{% extends 'base.html' %}


{% block content %}



    <section class="hero is-prime-color">
      <div class="hero-body">
        <div class="container">
          <h1 class="title">Écrire votre publication içi:</h1>
          <h2 class="subtitle">Collectionner et organiser autour d'un sujet, tout simplement.</h2>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="container" style="width: 60%">
      <div class="row">
        {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}

      </div>


      {% with messages = get_flashed_messages(with_categories=true) %}
      <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
        {% if messages %}
          {% for category, message in messages %}
            <div class="notification {{category}}">
              <button class="delete"></button>
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}

      <form  method="POST">

        {# This hidden_tag is a CSRF security feature. #}
        {{ form.hidden_tag() }}

        <div class="field">
          {{ form.post_title.label(class="label") }}
          <div class="control has-icons-left has-icons-right">
            {{ form.post_title(class="input", placeholder="Titre de la publication") }}
            <span class="icon is-small is-left">
              <i class="fas fa-user"></i>
            </span>
            <span class="icon is-small is-right">
              <i class="fas fa-check"></i>
            </span>
          </div>
          <p class="help is-success">Donner un titre à votre publication</p>
        </div>

        <div class="field">
          {{ form.post_summary.label(class="label") }}
          <div class="control">
            {{ form.post_summary(class="textarea", placeholder="Un bref résumé de votre publication") }}
          </div>
          <p class="help is-success">Donner un titre à votre publication</p>
        </div>

      <!-- Dates -->

        <div class="field">
          {{ form.start_date.label(class="label") }}
          <div class="control has-icons-left has-icons-right">
            {{ form.start_date(class="input", type="date") }}
            <span class="icon is-small is-left">
              <i class="fas fa-calendar-alt"></i>
            </span>
          </div>
          <p class="help is-success">Choisissez une date de début</p>
        </div>


        <div class="field">
          {{ form.end_date.label(class="label") }}
          <div class="control has-icons-left has-icons-right">
            {{ form.end_date(class="input", type="date") }}
            <span class="icon is-small is-left">
              <i class="fas fa-calendar-alt"></i>
            </span>
          </div>
          <p class="help is-success">Choisissez une date de fin</p>
        </div>


        <!-- Select Level -->
        <div class="field">
          {{ form.start_level.label(class="label") }}
          <div class="control">
            {{ form.start_level(class="input", type="select") }}
          </div>
          <p class="help is-success">Votre niveau de commencement</p>
        </div>


        <div class="field">
          {{ form.end_level.label(class="label") }}
          <div class="control">
            {{ form.end_level(class="input", type="select") }}
          </div>
          <p class="help is-success">Le niveau que vous espérez avoir à la fin.</p>
        </div>


        <!-- Choose a category for the post -->
        <div class="field">
          {{ form.post_tags.label(class="label") }}
          <div class="control has-icons-left has-icons-right">
            {{ form.post_tags(class="input", placeholder="python, sqlalchemy, flask") }}
            <span class="icon is-small is-left">
              <i class="fas fa-tag"></i>
            </span>
          </div>
          <p class="help is-success">Chaque catégorie doit etre séparer par une virgule</p>
        </div>


        {# Select the privacy level#}
        <div class="field">
          {{ form.post_privacy.label(class="label") }}
          <div class="control">
            {{ form.post_privacy(class="input", type="select") }}
          </div>
          <p class="help is-success">Qui peut voir votre collection</p>
        </div>


        <!-- Add links to the post -->
        <div class="u-margin-bottom-small">
          <h2 class="title is-4" >  Ajouter un lien à votre publication: </h2>
        </div>

        <figure class="notification">

            <div class="field">
              {{ form.link1_title.label(class="label") }}
              <div class="control has-icons-left has-icons-right">
                {{ form.link1_title(class="input", placeholder="Titre du lien") }}
                <span class="icon is-small is-left">
                  <i class="fas fa-heading"></i>
                </span>
              </div>
              <p class="help is-success">Donner un titre pour reconnaitre le lien facilement</p>
            </div>

            <div class="field">
              {{ form.link1.label(class="label") }}
              <div class="control has-icons-left has-icons-right">
                {{ form.link1(class="input", placeholder="Le lien") }}
                <span class="icon is-small is-left">
                  <i class="fas fa-link"></i>
                </span>
              </div>
              <p class="help is-success">Donner un titre pour reconnaitre le lien facilement</p>
            </div>

        </figure>

        <div id="input_fields_wrap">
        </div>



        <div id="btn_field">
          <hr class="hr-dotted">
          <a class="button is-text" id='add_field_button'>
            <span class="icon">
              <i class="fas fa-plus"></i>
            </span>
            <span>Ajouter un autre lien</span>
          </a>
          <hr class="hr-dotted">
        </div>


        {{ form.submit(class='button is-primary btn-lg') }}


      </form>

  </div>


    </section>




{% endblock %}

eduka/posts/templates/posts/post.html
<!--- post.html --->
{% extends 'base.html' %}

{% block content %}

<!-- Banner image top -->

    <section class="hero-section u-margin-bottom-small">
      <div class="container-fluid">
        <div class="row">
          <div class="u-center-text">
            <!--<h5>Hello, world! Full width Hero-unit header</h5> -->
          </div>
        </div>
      </div>
    </section>

    <div class="container"  >

        <div class="columns">

          <!-- LEFT COLUMN -->
          <div class="column is-2">
            <!-- // show the category and the social  -->
            <div class="container">
              <div class="tags">

                {% for tag in tags %}
                <a href="#" class="tag">{{ tag }}</a>
                {% endfor %}

              </div>
              <!--- Adding the social buttons here -->
              <hr>
              <div class="columns is-vcentered">
                <div class="column is-one-quarter" >

                  {% if current_user.had_clapped_post(post) %}
                  <a href="{{ url_for('users.clap_action', post_public_id=post.public_id, action='unclap') }}" class="button">
                    <span class="icon">
                      <i class="fas fa-heart"></i>
                    </span>
                  </a>
                  {% else %}
                  <a href="{{ url_for('users.clap_action', post_public_id=post.public_id, action='clap') }}" class="button">
                    <span class="icon">
                      <i class="far fa-heart"></i>
                    </span>
                  </a>

                  {%endif%}


                </div>
                <div class="column">
                  <p> <span>{{post.claps.count()}}</span></p>
                </div>
              </div>

              <div class="columns is-vcentered">
                <div class="column">
                  <a href="#" class="button">
                    <span class="icon">
                      <i class="fab fa-twitter"></i>
                    </span>
                  </a>
                </div>
              </div>

              <div class="columns is-vcentered">
                <div class="column">
                  <a href="#" class="button">
                    <span class="icon">
                      <i class="fab fa-facebook"></i>
                    </span>
                  </a>
                </div>
              </div>


              <!---// Adding the social buttons here -->
            </div>
          </div>

          <!-- *************** END LEFT COLUMN *********************** -->


          <!-- MIDDLE COLUMN -->
          <div class="column is-8">
            <h1 class="title is-2">{{ post.title }}</h1>
            <p class="subtitle is-6"><small class="text-muted">{{ post.date_posted | datetimeformat }}</small></p>
            {% if author.id == current_user.id %}
            <div class="u-margin-bottom-small">
              <a href="{{ url_for('posts.update_post', post_public_id=post.public_id) }}" class="button is-primary is-outlined"> Update</a>
              <a href="#" class="button is-danger">Delete</a>
            </div>

            {% endif %}

            <div class="u-margin-bottom-small">
              <p class="lead mt-4 mb-4"> {{ post.summary }} </p>
            </div>

            <!-- // show the post links and titles -->
            {% if links %}
            <div class="u-margin-bottom-small">
              <h3 class="subtitle is-3 ">Pour approfondir ses connaissances: </h3>
            </div>
            {% else %}

            <div class="u-margin-bottom-small">
              <p class="subtitle is-3"> Cette puplication ne contient pas de lien pour approfondir ses connaissances. Ajoutez-en: </p>
            </div>

            <div class="u-margin-bottom-small">
              <a href="#" class="button is-primary">Ajouter des liens</a>
            </div>

            {% endif %}



                <div class="cards-list">
                  {% for l in links %}

                  <a  href="{{ l.link_url }}" style="text-decoration: none;" target="_blank">
                    <div class="m_card 1">
                      <div class="card_image"> <img src="https://i.redd.it/b3esnz5ra34y.jpg" /> </div>
                      <div class="card_title title-white">
                        <p>{{ l.link_title }}</p>
                      </div>
                    </div>
                  </a>


                  {% endfor %}

                </div>

          </div>




                  <!-- RIGHT COLUMN -->
                  <div class="column is-2">
                    <div class="container">

                      <div class="columns is-vcentered">
                        <div class="column">
                          <!-- // show number of views and posted by:  -->
                              <p><small class="text-muted">added by:</small>
                                <a href=" {{ url_for('users.my_account', public_id=author.public_id) }}">
                                  {{ author.username }}
                                </a>
                              </p>
                        </div>
                      </div>

                      <hr>
                      <!-- second row -->
                      <div class="columns is-vcentered">
                        <div class="column">
                          <p><small class="text-muted">views:</small> {{ views }} fois</p>
                        </div>
                      </div>



                    </div>
                  </div>


        </div>


    </div>



{% endblock %}

eduka/posts/templates/posts/update_post.html
<!-- update_post.html -->

{% extends 'base.html' %}

{% block content %}

    <section class="hero is-warning">
      <div class="hero-body">
        <div class="container">
          <h1 class="title">Mettre à jour votre publication:</h1>
          <h2 class="subtitle">Mettre à jour très facilement une collection en éditant son contenue.</h2>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="container" style="width: 60%">
          <div class="row">
            {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
          </div>

          {% with messages = get_flashed_messages(with_categories=true) %}
          <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
            {% if messages %}
              {% for category, message in messages %}
                <div class="notification {{category}}">
                  <button class="delete"></button>
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}

          <form  method="POST">

            {# This hidden_tag is a CSRF security feature. #}
            {{ form.hidden_tag() }}

            <div class="field">
              {{ form.post_title.label(class="label") }}
              <div class="control has-icons-left has-icons-right">
                {{ form.post_title(class="input", placeholder="Titre de la publication") }}
                <span class="icon is-small is-left">
                  <i class="fas fa-user"></i>
                </span>
                <span class="icon is-small is-right">
                  <i class="fas fa-check"></i>
                </span>
              </div>
              <p class="help is-success">Donner un titre à votre publication</p>
            </div>

            <div class="field">
              {{ form.post_summary.label(class="label") }}
              <div class="control">
                {{ form.post_summary(class="textarea", placeholder="Un bref résumé de votre publication") }}
              </div>
              <p class="help is-success">Donner un titre à votre publication</p>
            </div>

            <!-- Dates -->

              <div class="field">
                {{ form.start_date.label(class="label") }}
                <div class="control has-icons-left has-icons-right">
                  {{ form.start_date(class="input", type="date") }}
                  <span class="icon is-small is-left">
                    <i class="fas fa-calendar-alt"></i>
                  </span>
                </div>
                <p class="help is-success">Choisissez une date de début</p>
              </div>


              <div class="field">
                {{ form.end_date.label(class="label") }}
                <div class="control has-icons-left has-icons-right">
                  {{ form.end_date(class="input", type="date") }}
                  <span class="icon is-small is-left">
                    <i class="fas fa-calendar-alt"></i>
                  </span>
                </div>
                <p class="help is-success">Choisissez une date de fin</p>
              </div>


              <!-- Select Level -->
              <div class="field">
                {{ form.start_level.label(class="label") }}
                <div class="control">
                  {{ form.start_level(class="input", type="select") }}
                </div>
                <p class="help is-success">Votre niveau de commencement</p>
              </div>


              <div class="field">
                {{ form.end_level.label(class="label") }}
                <div class="control">
                  {{ form.end_level(class="input", type="select") }}
                </div>
                <p class="help is-success">Le niveau que vous espérez avoir à la fin.</p>
              </div>

              <!-- Choose a category for the post -->
              <div class="field">
                {{ form.post_tags.label(class="label") }}
                <div class="control has-icons-left has-icons-right">
                  {{ form.post_tags(class="input", placeholder="python, sqlalchemy, flask") }}
                  <span class="icon is-small is-left">
                    <i class="fas fa-tag"></i>
                  </span>
                </div>
                <p class="help is-success">Chaque catégorie doit etre séparer par une virgule</p>
              </div>


              {# Select the privacy level#}
              <div class="field">
                {{ form.post_privacy.label(class="label") }}
                <div class="control">
                  {{ form.post_privacy(class="input", type="select") }}
                </div>
                <p class="help is-success">Qui peut voir votre collection</p>
              </div>




              {# div for the links - only add div if there are links to show #}

              {% if nbr_links > 0 %}

              {# user will need to click on the button to see links #}
              <!--- Update links and titles -->
              <h1 class="subtitle is-4">Voir tous vos liens</h1>
              <div id="show-links-wrapper">

                {# Links start here #}
                <!-- Add links to the post -->
                {% for l in post.links %}
                <figure class="notification">
          					<a class="button is-text" id='remove_field_button'>
          						<span class="icon">
          							<i class="far fa-trash-alt"></i>
          						</span>
          						<span>Retirer</span>
          					</a>
          					<hr class="hr-dotted">

          					<label class="label" for="link1_title">ajouter un title pour le lien:</label>
          					<div class="control has-icons-left has-icons-right">
          						<input class="input" id="link1_title" name="link1_title" placeholder="Titre du lien" type="text" value="{{l.link_title}}">
          						<span class="icon is-small is-left">
          							<i class="fas fa-heading"></i>
          						</span>
          					</div>
          					<p class="help is-success">Donner un titre pour reconnaitre le lien facilement</p>

          				<div class="field">
          					<label class="label" for="link1">ajouter un lien:</label>
          					<div class="control has-icons-left has-icons-right">
          						<input class="input" id="link1" name="link1" placeholder="Le lien" type="text" value="{{ l.link_url }}">
          						<span class="icon is-small is-left">
          							<i class="fas fa-link"></i>
          						</span>
          					</div>
          					<p class="help is-success">Donner un titre pour reconnaitre le lien facilement</p>
          			</figure>

                {% endfor %}

                {# Links ends here#}
              </div>


                <div class="btn_show_field">
                  <hr class="hr-dotted">
                  <a id='show_links_btn' onclick="showLinks()">
                    <span class="icon">
                      <i class="fas fa-plus"></i>
                    </span>
                    <span>Cliquer pour voir les liens</span>
                  </a>
                  <hr class="hr-dotted">
                </div>

              {% endif %}



            {# wrapper to add the links field #}
              <h1 class="subtitle is-4">Ajouter d'autres liens</h1>
              <div id="update_fields_wrap">
              </div>

            {# adding the links and title dynamicaly #}
            {# user will need to click on the button to update links #}
            <!--- Update links and titles -->
              <div class="btn_add_field">
                <hr class="hr-dotted">
                <a id='update_links_btn'>
                  <span class="icon">
                    <i class="fas fa-plus"></i>
                  </span>
                  <span>Ajouter un nouveau lien</span>
                </a>
                <hr class="hr-dotted">
              </div>

            {{ form.submit(class='button is-primary') }}
            <a href="{{url_for('posts.show_post', post_public_id=post.public_id)}}" class="button is-primary is-outlined">Annuler</a>


          </form>



      </div>



    </section>
     {# need to add this to a separate js file #}
    <script>
      function showLinks() {
        var x = document.getElementById("show-links-wrapper");
        if (x.style.display === "none") {
          x.style.display = "block";
        } else {
          x.style.display = "none";
        }
      }
    </script>






{% endblock %}