eduka/core/views.py
## views.py in core
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, redirect, flash
from eduka.models import Post



core_blueprint = Blueprint('core',
                            __name__,
                            template_folder='templates/core',
                            static_url_path='/core/static',
                            static_folder='static')


@core_blueprint.route('/')
def home():
    title = 'eduka! Apprendre mieux!'


    return render_template('home.html', title=title)


@core_blueprint.route('/about')
def about():
    title = 'eduka! À propos de nous'
    return render_template('about.html', title=title)

@core_blueprint.route('/collections')
def show_collections():
    title = 'eduka! | Public collections disponible'

    ## get all the public posts

    p = Post.query.filter(Post.privacy_level == 'pbl')
    p_desc = p.order_by(Post.date_posted.desc())
    posts = p_desc.limit(50).all()

    return render_template('collection.html', title=title, posts=posts)

eduka/core/templates/core/about.html
<!-- ABOUT.HTML -->


{% extends 'base.html' %}


{% block content %}




  <section class="section">
    <div class="container">
      <h1 class="title is-1">Bienvenue chez eduka!</h1>

      <div class="columns is-desktop">
        <div class="column">
          <div class="content is-medium">
            <h3 >  À propos du service eduka!.</h3>
            <p >
              Avec la multiplication presqu'a l'infini de l'information sur web disponible, il peut être assez diffficile de se souvenir de tous les sites internet visiter lors des recherches sur un sujet particulier.
              Bien entendu, vous pouvez utiliser les "Bookmarks" (marque-pages disponible par le biais de votre navigateur internet habituel), mais on le sait que trop bien que cela peut devenir un très grand fouilli
              très rapidement et que l'on se rapelle pas souvent de reconsulter ses fameuses "Bookmarks".
            </p>
            <p>C'est pour cela que l'on a conçu <strong>eduka!</strong></p>
            <p>
              Le site qui vous aide à <strong>regrouper, organiser et visualiser</strong> toutes les informations
              sur un thème/ sujet très simplement. Vous pouvez créer des marque-pages par sujet appeler "collection". Pour chaque collection, vous pouvez:
            </p>
            <ul>
              <li>Donner un titre qui caractérise le thème/ sujet de la collection</li>
              <li>Ajouter un résumé qui vous permetra de comprendre le sujet</li>
              <li>Si le but est 'apprentissage', vous pourrez noter votre niveau de complexité du sujet mais aussi la progresion que vous souhaiter obtenir à la fin de la lecture, visonnage (débutant, intermédiaire, avancé ou expert)</li>
              <li>Le temps que vous estimiez nécessaire afin d'obtenir le niveau souhaiter</li>
              <li>Classer par tags (étiquette) comme: Javascrit, Python, Économie, Sociologie ...</li>
              <li>Ajouter autant de lien au thème/sujet pour créer la collection </li>
              <li>Décider si votre collection est privée ou public</li>
            </ul>
          </div>


        </div>
      </div>
    </div>


  </section>

  <!-------- section rejoignez-nous ------->

  <section class="hero is-warning is-medium is-bold">
    <div class="hero-body">
      <div class="container">
        <div class="columns is-desktop is-centered">
          <div class="column has-text-centered">
            <h1 class="title is-1"> Commencez à collectionner et à donner tous son sens à l'information</h1>
            {% if current_user.is_authenticated %}
            <a  href="{{url_for('posts.add_post')}}" class="button is-primary">Je crée une collection</a>
            {% else %}
            <a href="{{url_for('users.registration')}}" class="button is-info">Je m'inscris gratuitement!</a>
            {% endif %}
        </div>
      </div>
    </div>
  </section>


  <!-------- //section rejoignez-nous ------->

{% endblock content%}

{% block footer %}
{% include 'footer.html' %}
{% endblock footer%}

eduka/core/templates/core/base.html
<!--- BASE.HTML -->


<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title> {{ title }}</title>
<!--
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" rel="stylesheet">
-->
    <!-- Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
  <!--  <link media="all" type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-tooltip@2.0.2/dist/css/bulma-tooltip.min.css">
    <link rel="stylesheet" href="{{ url_for('core.static', filename='css/bulma-calendar.min.css') }}"> -->
    <link rel="stylesheet" href="{{ url_for('core.static', filename='css/style.css') }}">
  </head>
  <body>

    <header>

      <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" href="{{ url_for('core.home') }}">
            <img src="https://first-rep-eduka.s3.eu-west-3.amazonaws.com/site-logos/eduka_logo_small.png" width="112" height="28">
          </a>

          <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navMenu">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div class="navbar-menu" id="navMenu">
          <div class="navbar-start">
            <a class="navbar-item"  href="{{ url_for('core.home') }}">Home</a>
            <a class="navbar-item"  href="{{ url_for('core.about') }}">À propos de</a>
            <a class="navbar-item"  href="{{ url_for('core.show_collections') }}">Collections</a>
            {% if current_user.is_authenticated  %}
            <a href="{{ url_for('posts.add_post') }}" class="navbar-item">Publier</a>
            <a href="{{ url_for('users.my_account', public_id=current_user.public_id)}}" class="navbar-item"> Mon Compte</a>
            {% endif %}

          </div>

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                {% if current_user.is_authenticated  %}
                <a  href="{{ url_for('users.logout') }}" class="button is-primary"><strong>Déconnection</strong></a>
                {% else %}
                <a  href="{{ url_for('users.registration') }}" class="button is-primary"><strong>Inscription</strong></a>
                <a href="{{ url_for('users.login') }}" class="button is-light">Connexion</a>
                {% endif %}

              </div>
            </div>
          </div>
        </div>

      </nav>

    </header>



    <div id="content">
      <main class="app-content">{% block content %} {% endblock %}</main>
    </div>
    <div id="footer">{% block footer %}{% endblock %}</div>





    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="{{ url_for('core.static', filename='js/add_input_field.js') }}"></script>
    <script src="{{ url_for('core.static', filename='js/toggle-slides.js') }}"></script>
    <!--<script src="{{ url_for('core.static', filename='js/doc.js') }}"></script>
    <script src="{{ url_for('core.static', filename='js/bulma-calendar.min.js') }}"></script>
    <script src="{{ url_for('core.static', filename='js/main.js') }}"></script> -->
  <!--  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->

  </body>
</html>

eduka/core/templates/core/collection.html
<!-- collection.html -->


{% extends 'base.html' %}

{% block content %}

    <section class="hero is-link">
      <div class="hero-body">
        <div class="container">
          <h1 class="title">Toutes les collections disponibles publiquement</h1>
          <h2 class="subtitle">Votez, inspirez-vous des meilleurs collections disponible.</h2>
        </div>
      </div>
    </section>


    <section class="section">
      <div class="container">
        <div class="row">
          <div class="columns">

            <div class="column is-2-widescreen">
              {# LEFT SIDE #}
              <section class="section">
                <h3 class="subtitle is-4"> Filtrer par date:</h3>
                {# start of the card - need to change this for a table #}
                <div class="menu">
                  <ul class="menu-list">
                    <li> <a href="#" class="is-active">All</a> </li>
                    <li> <a href="#">Récent</a> </li>
                    <li> <a  href="#">Il y a une semaine</a> </li>
                    <li> <a href="#">Il y a deux semaine</a> </li>
                    <li> <a href="#">Il y a un mois</a> </li>
                  </ul>
                </div>

              </section>

              <section class="section">
                <h3 class="subtitle is-4"> Filtrer par tags:</h3>
                {# start of the card - need to change this for a table #}
                <div class="menu">
                  <ul class="menu-list">
                    <li> <a href="#" class="is-active">All</a> </li>
                    <li> <a href="#">Python</a> </li>
                    <li> <a  href="#">Javascript</a> </li>
                    <li> <a href="#">Flask</a> </li>
                    <li> <a href="#">Git</a> </li>
                  </ul>
                </div>

              </section>
            </div>


            {# RIGHT SIDE - SHOW COLLECTIONS#}
            <div class="column is-10">
              <section class="section">
                <h3 class="subtitle is-4"> Mes collections</h3>
                {# we will dive the different colums#}
                <div class="columns is-multiline">
                  {# start the for loop to get all the posts #}
                  {% for post in posts %}
                    <div class="column is-one-third">
                      {# start of the card #}
                      <div class="card">
                        <div class="card-image">
                          <figure class="image is-4by3">
                            <img src="{{ post.post_image_link }}" alt="Placeholder image">
                          </figure>
                        </div>
                        <div class="card-content">
                          <div class="media">
                            <div class="media-content">
                              <p class="title is-5">{{ post.title }}</p>
                              <p class="subtitle is-6">{{ post.date_posted|datetimeformat }}</p>
                            </div>
                          </div>

                          <div class="content">
                            {{ post.summary|truncate(70, True)|safe }}
                          </div>
                          <a href="{{ url_for('posts.show_post',post_public_id=post.public_id)}}" class="button is-primary issmall">Voir collection</a>
                        </div>
                      </div>
                      {# end of the card #}
                    </div>
                  {% endfor %}

                </div>

              </section>

            </div>

          </div>

      </div>


    </section>


{% endblock content %}

{% block footer %}
{% include 'footer.html' %}
{% endblock footer%}

eduka/core/templates/core/footer.html
<!-- The footer for pages that need it -->


<!-------- FOOTER Start here ---------->

<footer class="footer is-dark-color">
  <div class="columns is-vcentered">
      <!-------- Left side column ---------->
    <div class="column is-half-desktop is-half-tablet">

      <div class="navbar-brand">
        <a class="navbar-item" href="{{ url_for('core.home') }}">
          <img src="https://first-rep-eduka.s3.eu-west-3.amazonaws.com/site-logos/eduka_logo_white_small_white.png" width="112" height="28">
        </a>
      </div>
    </div>

    <!-------- Middle column ---------->
    <div class="column">
      <div class="content">
        <h4> Produit</h4>
        <a href="#">Comment ça marche</a> <br>
        <a href="{{ url_for('posts.add_post') }}">Publier</a> <br>
        <a href="{{ url_for('core.show_collections') }}">Toutes les collections</a><br>
      </div>
    </div>

    <!-------- Right side column ---------->
    <div class="column">
      <div class="content">
        <h4> eduka!</h4>
        <a href="{{ url_for('core.about') }}">à propos</a> <br>
        <a href="{{ url_for('users.registration') }}">Créer un compte gratuit</a> <br>
        <a href="{{ url_for('users.login') }}">Connexion</a><br>
      </div>
    </div>
  </div>
</footer>

eduka/core/templates/core/home.html
<!-- HOME.HTML -->


{% extends 'base.html' %}


{% block content %}
      <!-------- top section: intro ------->
      <section class="hero is-prime-color is-section1" id="section1">
        <div class="hero-body">
          <div class="container">
            <div class="columns is-vcentered">

              <div class="column is-two-fifths-desktop is-full-tablet has-text-left-desktop has-text-centered-mobile has-text-centered-tablet ">

                <div class="columns">
                  <div class="column">
                    {# Column left for the text#}
                    <h1 class="title is-2">  La nouvelle façon d'organiser les infos pertinentes par thème.</h1>
                    <div class="content is-medium ">
                      <p >Le site qui vous aide à regrouper, organiser et visualiser toutes
                        les informations sur un thème/ sujet tous simplement.
                      </p>
                    </div>

                  </div>
                </div>


                <div class="colums" >
                  {% if current_user.is_authenticated %}
                  <div class="column">
                    <a  href="{{url_for('posts.add_post')}}" class="button is-primary">Je crée une collection</a>
                  </div>
                  {% else %}
                  <div class="column" >
                    <a href="{{url_for('users.registration')}}" class="button is-info">Je m'inscris!</a>
                  </div>
                  <div class="column">
                    <a href="#section-hiw" class="button is-primary is-outlined">Comment ça marche?</a>
                  </div>
                  {% endif %}

                </div>




              </div>

              <div class="column">
                {# Column right for the image#}
                <figure class="image is-5by4">
                  <img src="https://www.beekast.com/wp-content/uploads/2019/06/fonctionnalites-beekast-FR.png">
                </figure>
              </div>

            </div>
          </div>
        </div>
      </section>

      <!-------- //top section: intro ------->

      <!-------- section on showing companies using the service ------->

      <section class="hero has-background-light" id="section2">
        <div class="hero-body">
          <div class="container">
            <div class="level">
              <div class="level-item has-text-centered">
                <figure class="image is-64x64">
                  <img src="https://www.bluleadz.com/hs-fs/hubfs/Brand%20Logos/Nasa.png?width=363&height=300&name=Nasa.png" alt="Une image">
                </figure>
              </div>

              <div class="level-item has-text-centered">
                <figure class="image is-64x64 ">
                  <img src="https://www.bluleadz.com/hs-fs/hubfs/Brand%20Logos/500px-United_Parcel_Service_logo_2014.svg.png?width=252&height=300&name=500px-United_Parcel_Service_logo_2014.svg.png" alt="Une image">
                </figure>
              </div>

              <div class="level-item has-text-centered">
                <figure class="image is-64x64">
                  <img src="https://www.bluleadz.com/hs-fs/hubfs/Brand%20Logos/3M.png?width=300&height=158&name=3M.png" alt="Une image">
                </figure>
              </div>

            </div>
          </div>
        </div>
      </section>
          <!-------- //section on showing companies using the service ------->

            <!-------- section on showing the collections ------->
      <section class="hero" id="section3">
        <div class="hero-body">
          <div class="container">
            <div class="columns is-centered">
              <div class="column has-text-centered">
                <h1 class="title is-1">  Intelligent Et Intuitive.</h1>
                <div class="content is-medium">
                  <p>Une manière intelligente d'organiser les liens des
                    sites web par thème pour mieux comprendre un sujet.
                  </p>

                </div>


                <figure class="image is-5by3">
                  <img src="https://static.buffer.com/marketing/static/screenshots/buffer-publish-dashboard@2x.jpeg" alt="Une image">
                </figure>
              </div>

            </div>
          </div>
        </div>
      </section>
      <!-------- //section on showing the collections ------->

      <!-------- section how it works ------->
      <section class="hero" id="section-hiw">
        <div class="hero-body">
          <div class="container">

              <div class="columns is-desktop is-vcentered">

                <div class="column is-two-fifths-desktop is-full-tablet has-text-centered-mobile has-text-centered-tablet">
                  {# Column left for the text#}
                  <h1 class="title is-3">Comment Ça Marche?</h1>
                  <div class="content is-medium">
                    <p>Créer des collections en quelques clics
                      retrouvez vos collections sur votre page personnelle ou ouvrez
                      les à la communauté.
                    </p>

                  </div>

                  {% if current_user.is_authenticated %}
                  <a  href="{{url_for('posts.add_post')}}" class="button is-primary">Je crée une collection</a>
                  {% else %}
                  <a href="{{url_for('users.registration')}}" class="button is-info">Je m'inscris gratuitement!</a>
                  {% endif %}



                </div>

                <div class="column">
                  {# Column right for the image#}
                  <figure class="image is-5by4">
                    <img src="https://static.buffer.com/marketing/static/illustrations/buffer-publish-planning@2x.jpeg" alt="Une image">
                  </figure>
                </div>

              </div>

            <!-- end of first row -->

              <!-- begginning of second row -->
              <div class="columns is-desktop is-vcentered" >

                <!-- 1st column for 1º -->
                <div class="column has-text-centered">

                  <!-- create row for image -->
                    <div class="columns is-desktop is-vcentered">
                      <div class="column has-text-centered is-paddingless">
                        <figure class="image 256x256 is-inline-block">
                          <img src="https://static.buffer.com/marketing/static/ui/buffer-publish-scheduling@2x.jpeg" alt="Une image">
                        </figure>
                      </div>
                    </div>

                    <!-- create row for text -->
                      <div class="columns">
                        <div class="column">
                          <p class="title is-4 is-marginless">Inscription</p>
                          <p> Créer un compte qui vous permettra de sauvegarder vos collections facilement.</p>
                        </div>
                      </div>

                </div>


                <!-- // end 1º -->


                <!-- 1st column for 2º -->
                <div class="column has-text-centered">

                  <!-- create row for image -->
                    <div class="columns is-desktop is-vcentered">
                      <div class="column has-text-centered is-paddingless">
                        <figure class="image 256x256 is-inline-block">
                          <img src="https://static.buffer.com/marketing/static/ui/buffer-publish-scheduling@2x.jpeg" alt="Une image">
                        </figure>
                      </div>
                    </div>

                    <!-- create row for text -->
                      <div class="columns">
                        <div class="column">
                          <p class="title is-4 is-marginless">Publier une collection</p>
                          <p> Choisir un titre, une description et ajouter pour la collection, puis ajouter autant de liens pour cette collection (thème)</p>
                        </div>
                      </div>

                </div>


                <!-- // end 2º -->

                <!-- 1st column for 3º -->
                <div class="column has-text-centered">

                  <!-- create row for image -->
                    <div class="columns is-desktop is-vcentered">
                      <div class="column has-text-centered is-paddingless">
                        <figure class="image 256x256 is-inline-block">
                          <img src="https://static.buffer.com/marketing/static/ui/buffer-publish-scheduling@2x.jpeg" alt="Une image">
                        </figure>
                      </div>
                    </div>

                    <!-- create row for text -->
                      <div class="columns">
                        <div class="column">
                          <p class="title is-4 is-marginless">Social</p>
                          <p> Applaudissez les collections que vous aimez. Choississez quelle collection que vous voulez mettre public.</p>
                        </div>
                      </div>

                </div>


                <!-- // end 3º -->

              </div>
          </div>
        </div>
      </section>
      <!-------- //section how it works ------->


      <!-------- section rejoignez-nous ------->

      <section class="hero has-background-warning is-medium is-bold">
        <div class="hero-body">
          <div class="container">
            <div class="columns is-centered">
              <div class="column has-text-centered">
                <h1 class="title is-2"> Commencez à collectionner et à donner tous son sens à l'information</h1>
                {% if current_user.is_authenticated %}
                <a  href="{{url_for('posts.add_post')}}" class="button is-primary">Je crée une collection</a>
                {% else %}
                <a href="{{url_for('users.registration')}}" class="button is-info">Je m'inscris gratuitement!</a>
                {% endif %}
            </div>
          </div>
        </div>
      </section>


      <!-------- //section rejoignez-nous ------->





{% endblock content%}

{% block footer %}
{% include 'footer.html' %}
{% endblock footer%}